### ISSUE TITLE
Unable to bypass Thumbprint validations

### ISSUE THREAD

**Issue by Ntobon** [knmtc/RemoteAuth#2]
There seems to be an issue on the module: 
https://github.com/auth0/passport-wsfed-saml2

Even if there is a valid thumbprint given in the configuration, the module seems to be unable to match the thumbprints and throws this error.

error Error: Invalid thumbprint (configured: ‎C2C561DDA76F69B0EA223C047A88113BF8CCD8CD, ‎C2C561DDA76F69B0EA223C047A88113BF8CCD8CD. calculated: C2C561DDA76F69B0EA223C047A88113BF8CCD8CD)
14|RemoteA |     at SAML.validateSignature (/var/node/RemoteAuth/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/saml.js:102:23)
14|RemoteA |     at SAML.validateSamlAssertion (/var/node/RemoteAuth/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/saml.js:252:8)
14|RemoteA |     at /var/node/RemoteAuth/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/strategy.js:63:16
14|RemoteA |     at WsFederation.retrieveToken (/var/node/RemoteAuth/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/wsfederation.js:62:5)
14|RemoteA |     at WsFedSaml2Strategy._authenticate_saml (/var/node/RemoteAuth/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/strategy.js:60:15)
14|RemoteA |     at loaded (/var/node/RemoteAuth/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/strategy.js:166:16)
14|RemoteA |     at NullStore.verify (/var/node/RemoteAuth/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/state/null.js:9:3)
14|RemoteA |     at verifyState (/var/node/RemoteAuth/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/strategy.js:149:26)
14|RemoteA |     at executeWsfed (/var/node/RemoteAuth/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/strategy.js:170:7)
14|RemoteA |     at WsFedSaml2Strategy.authenticate (/var/node/RemoteAuth/node_modules/passport-wsfed-saml2/lib/passport-wsfed-saml2/strategy.js:267:5)

**Comment by Ntobon** [comment]
As a workaround thumbprint checks were disabled inside the module.
https://github.com/auth0/passport-wsfed-saml2/blob/master/lib/passport-wsfed-saml2/saml.js#L107
by always returning true in this check.
